server {
    listen 80;
    server_name _;

    location / {
        proxy_pass http://127.0.0.1:3939;
    }

    location ~* /internal/ {
        allow 127.0.0.1;
        deny all;
        proxy_pass http://127.0.0.1:3939;
    }
}

server {
    listen 80;
    server_name downloader;
    location / {
        proxy_pass http://127.0.0.1:3940;
    }
}
