services:
  webarchive:
    build: ./webarchive
    ports:
      - "11001:5000"
    networks:
      - ctf-net
    depends_on:
      - internal

  internal:
    build: ./internal
    networks:
      - ctf-net

networks:
  ctf-net:
    driver: bridge
