[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
logfile_backups=0

[program:service]
command=node index.js
directory=/app
user=root
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/null
stdout_logfile_maxbytes=0

[program:nginx]
command=nginx -g 'daemon off;'
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/null